[[plugins]]
  package = "netlify-plugin-inline-source"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build]
  command = "gatsby build"
  publish = "public/"
  functions = "functions/"

[build.environment]
  GO_VERSION = "1.16"

[[headers]]
  for = "/*"
  [headers.values]
    same-site = '''
    None,
    Secure
    '''
    content-security-policy = '''
     default-src *;
     style-src 'self' 'unsafe-inline';
     font-src 'self' data:;
     script-src 'self' 'unsafe-inline' 'unsafe-eval' mapbox.com");
     '''

[[headers]]
  for = "/webfonts/GilroyMedium.woff2"
  [headers.values]
    crossorigin = "anonymous"
    cache-control = '''
    max-age=604800,
    no-cache,
    public'''

[[headers]]
  for = "/webfonts/GilroyMedium.woff"
  [headers.values]
    crossorigin = "anonymous"
    cache-control = '''
    max-age=604800,
    no-cache,
    public'''

[[headers]]
  for = "/webfonts/MacklinTextLight.woff2"
  [headers.values]
    crossorigin = "anonymous"
    cache-control = '''
    max-age=604800,
    no-cache,
    public'''

[[headers]]
  for = "/webfonts/MacklinTextLight.woff"
  [headers.values]
    crossorigin = "anonymous"
    cache-control = '''
    max-age=604800,
    no-cache,
    public'''

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
