[[plugins]]
  package = "netlify-plugin-inline-source"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build]
  base = "/"
  command = "gatsby build"
  publish = "public/"
  functions = "functions/"

[build.environment]
  GO_VERSION = "1.16"

[[headers]]
  for = "/*"
  [headers.values]
    Set-Cookie = '''
    _gid=GA1.2.1584989245.1615005592;
    _ga=GA1.2.558205032.1613277221;
    SameSite=None;
    Secure
    '''

[[headers]]
  for = "/webfonts/GilroyMedium.woff2"
  [headers.values]
    crossorigin = "anonymous"
    cache-control = '''
    max-age=604800,
    no-cache,
    public'''

[[headers]]
  for = "/webfonts/GilroyMedium.woff"
  [headers.values]
    crossorigin = "anonymous"
    cache-control = '''
    max-age=604800,
    no-cache,
    public'''

[[headers]]
  for = "/webfonts/MacklinTextLight.woff2"
  [headers.values]
    crossorigin = "anonymous"
    cache-control = '''
    max-age=604800,
    no-cache,
    public'''

[[headers]]
  for = "/webfonts/MacklinTextLight.woff"
  [headers.values]
    crossorigin = "anonymous"
    cache-control = '''
    max-age=604800,
    no-cache,
    public'''

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
